### ISSUE TITLE
Add an intercoms allowing researchers to speak into SCP chambers

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#634]
https://civilnetworks.net/community/threads/a-proper-intercom-system-for-scp-chambers-that-can-freely-speak.25287/#post-182941
This will add a intercome that would allow a researcher to speak into the chamber so D-class and SCPs within may here

**Comment by liondadev** [comment]
## Todo
- [x] Toolgun
  - [x] CRUD Groups
  - [x] Left Click to create intercom
  - [x] Right Click to create speaker
    - [x] Speaker model should change depending on if the speaker is being placed on a wall or on the floor
    - [x] Microphone model should change depending on if the speaker is being placed on a floor or wall
- [x] Microphone
  - [x] Wall Model
  - [x] Floor Model
  - [x] Press USE to toggle on or off
  - [x] Place light on the front of the model
- [x] Speaker
  - [x] Wall Model
  - [x] Floor Model
  - [x] Green light on front when active
- [x] Optimizations
  - [x] Figure out a way for this to not lag the hell out of the server.

This could also just be an addition to the phone system, allowing the phones in the viewing areas to act as intercom microphones for speakers inside the chambers. If two-way communication is needed, there could be locked down phones in the chambers that could only call the viewing areas. This would likely require a way of putting the phones on speaker phone.

**Comment by liondadev** [comment]
## Pre-Release Changes
- [x] Configurable radius in the toolgun placer
- [x] Different effects when you are in a different spot relative to the intercom
  - [x] Don't play effects if you're close to the intercom that is being spoken into
  - [x] Use DarkRP's inRoom effect as well?
- [x] Support text chat
